apiVersion: v1
kind: Service
metadata:
  name: error-service
spec:
  type: NodePort  # Change from ClusterIP to NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30023  # Specify nodePort here
  selector:
    app: 403-error


