apiVersion: v1
kind: Service
metadata:
  name: error-service
spec:
  type: NodePort  # Change from ClusterIP to NodePort
  ports:
    - port: 80
      targetPort: 30023
      nodePort:  # Specify nodePort here
  selector:
    app: 403-error


