---
apiVersion: v1
kind: Service
metadata:
  name: error-service
spec:
  selector:
    app: 403-error
  ports:
    - name: http
      port: 80
      targetPort: 9001
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 403-error
  namespace: default
spec:
  replicas: 1  # Number of pod replicas
  selector:
    matchLabels:
      app: 403-error
  template:
    metadata:
      labels:
        app: 403-error
    spec:
      containers:
        - name: 403-error
          image: ghcr.io/saisairepo/403-error:v2.2
          ports:
            - containerPort: 9001
          imagePullPolicy: Always
      imagePullSecrets:
        - name: error-secret
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: saisai.local
      http:
        paths:
          - path: /403-error
            pathType: Prefix
            backend:
              service:
                name: error-service
                port:
                  number: 80
